### ISSUE TITLE
Add instructions for manual JAR installation

### ISSUE THREAD

**Issue by seb-ster** [fruggy83/openocean#103]
Since this project relies on manual installation of the binding. I would like to suggest adding a set of instructions on how to do this.

The [OpenHAB documentation](https://www.openhab.org/docs/configuration/addons.html#through-manually-provided-add-ons) provides some information on manual installation. But on my Openhabian 3.0.1 Build atleast the [path for manual installation](https://www.openhab.org/docs/installation/linux.html#file-locations) did not exist.

I would appreciate to get some feedback from the Openocean documentation on what kind of results/effects one would see after placing the JAR in the correct folder. Maybe even some tips on trouble shooting when things go wrong.

I realize this could also be added to the official openHAB docs, but i have the feeling they more or less discourage adding stuff manually.

For my installation I tried creating the path manually and downloading the latest JAR (2.5.2) into it with WGET. This appeared to not have any effect. No log entries, no package in the feature:list.

After moving the JAR to the regular addons folder atleast I get a log entry informing me there was an error while starting the bundle.

`2021-02-01 13:12:18.138 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.openocean-2.5.2-SNAPSHOT.jar

org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.openocean [240]

  Unresolved requirement: Import-Package: org.eclipse.smarthome.config.core

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]

	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]`

From some Googeling it appears that it have been [changes to Namespaces with OH3](https://community.openhab.org/t/guide-binding-development-changes-for-openhab-3-from-2-5-x/104134) and that might be the cause of the issue.
I would be happy to open a separate Issue for this.

**Comment by fruggy83** [comment]
Hi @seb-ster 

good points. The current release 2.5.2 does not work with OH3. I will update the release and the docs this weekend. Thanks a lot for your hints 👍

Best regards
Daniel
