### ISSUE TITLE
Openocean v3.1.0.0.jar doesn‘t work with OH 3.1

### ISSUE THREAD

**Issue by diRk262** [fruggy83/openocean#110]
Hey Daniel,
I just updated my OH to 3.1.
Unfortunately your latest .jar v3.1.0.0 doesn‘t work anymore.
Could you please compile a new version which works with OH3.1?
Looks like the official binding is not merged with all changes you implemented.

`2021-06-28 21:46:48.103 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.openocean-3.1.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.openocean [283]
  Unresolved requirement: Import-Package: javax.measure; version="[1.0.0,2.0.0)"
	at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:440) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.8] `

Thank you,
Best regards 
Dirk

**Comment by Schatte79** [comment]
Hello, I wanted to ask if there is already something new. Unfortunately, the bundle in OH 3.1 no longer works for me too.
thanks

**Comment by diRk262** [comment]
Hi @Schatte79 ,
a friend of mine was able to compile the bundle with the needed files to let it work with OH3.1.
You can download it here:
https://www.gwozdz.rocks/org.openhab.binding.openocean-3.1.0.jar

**Comment by fruggy83** [comment]
HI, I just released a new version compiled against 3.2 snapshot. It works with OH 3.1 too.

**Comment by diRk262** [comment]
Hi @fruggy83 ,
nice to hear from you again. I thought you maybe stopped working on this binding.
Happy to see you are still working on it.

Is in your 3.2 release anything new compared to your 3.1.0.0 version? Last time we talked you were working on the implementation for the F4HK14 telegrams I think.

**Comment by fruggy83** [comment]
Hi @diRk262,

I have not stopped working on this binding. I just did not found enough time to work on it, to much other interesting projects 😃 

Currently v3.2 just contains a more advanced RockerSwitch implementation. However I am working on this F4HK14 issue too. I just want to combine it with some other panel EEP. I am not sure if it gets merged into official 3.2. A sync with the official 3.2 is also outstanding (D2-06-50 is missing here).

**Comment by diRk262** [comment]
Hi @fruggy83 ,
other projects are great. My favorite project is still my smarthome controlled by your binding..haha 🥇 
Please let me know when I can support you with testing new implementatios or EEPs.
My Eltako setup has grown even more over the past few months.. I needed to install two extra power supplies so that the Bus has enough voltage to power all the devices 😃

Maybe you can support even more devices in cooperation with me.
Best regards Dirk
