### ISSUE TITLE
Add EEP D2-11-01

### ISSUE THREAD

**Issue by dominikkv** [fruggy83/openocean#64]
This EEP consists of three types:

- Type A: device requests data
- Type B: controller sends data
- Type C: device sends data

So the device can send type A or C, and the controller has to answer with type B.

For a successfull communication, we need

- this EEP
- the ability to respond to telegrams, like prepared in #63 
- support for SmartACK

**Comment by fruggy83** [comment]
All requested changes are implemented now and tested with a Thermokon SR06.

**Comment by ratiomatic** [comment]
Hi @fruggy83,
Congratulations on the much awaited bidirectional thermostat binding!
I just installed the new release 2.5.2 beta openocean and tested on my **SR06 RH 2T** and did not get any device found:
19:54:03.176 [WARN ] [ommon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_65]
        at java.lang.Long.parseLong(Long.java:601) ~[?:1.8.0_65]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.informListeners(EnOceanTransceiver.java:422) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.processMessage(EnOceanTransceiver.java:313) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.receivePackets(EnOceanTransceiver.java:200) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.access$3(EnOceanTransceiver.java:192) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver$1.run(EnOceanTransceiver.java:163) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_65]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_65]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_65]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

Is the D2-11-02 not supported? It just adds the humidity value. Will you please make the modification to D2-11-01 and release the D2-11-02 also? I will greatly appreciate the effort!
