### ISSUE TITLE
Eltako TF61J-230V

### ISSUE THREAD

**Issue by vio2000** [fruggy83/openocean#86]
Hi @fruggy83,
another problem occurs.
I bought a Eltako TF61J-230V
Unfortunately, I can't find it in the inbox. In the log, I get the following errors:
2020-01-09 20:44:53.476 [INFO ] [covery.EnOceanDeviceDiscoveryService] - Stopping EnOcean discovery scan

2020-01-09 20:44:53.478 [INFO ] [covery.EnOceanDeviceDiscoveryService] - Starting EnOcean discovery and accepting teach in requests

2020-01-09 20:45:11.210 [DEBUG] [ernal.transceiver.EnOceanTransceiver] - RADIO_ERP1 with RORG MSC for  payload D100D0FF000004360589AE460100FFFFFFFF4900 received

2020-01-09 20:45:11.212 [ERROR] [ernal.transceiver.EnOceanTransceiver] - Exception in informListeners

	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.informListeners(EnOceanTransceiver.java:296) [bundleFile:?]

	at org.openhab.binding.enocean.internal.transceiver.EnOceanESP3Transceiver.processMessage(EnOceanESP3Transceiver.java:154) [bundleFile:?]

	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.receivePackets(EnOceanTransceiver.java:255) [bundleFile:?]

	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.access$2(EnOceanTransceiver.java:248) [bundleFile:?]

	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver$1.run(EnOceanTransceiver.java:198) [bundleFile:?]

2020-01-09 20:45:11.730 [DEBUG] [ernal.transceiver.EnOceanTransceiver] - RADIO_ERP1 with RORG MSC for  payload D100D0FE03030100740589AE460000FFFFFFFF4900 received

2020-01-09 20:45:11.732 [ERROR] [ernal.transceiver.EnOceanTransceiver] - Exception in informListeners

	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.informListeners(EnOceanTransceiver.java:296) [bundleFile:?]

	at org.openhab.binding.enocean.internal.transceiver.EnOceanESP3Transceiver.processMessage(EnOceanESP3Transceiver.java:154) [bundleFile:?]

	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.receivePackets(EnOceanTransceiver.java:255) [bundleFile:?]

	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.access$2(EnOceanTransceiver.java:248) [bundleFile:?]

	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver$1.run(EnOceanTransceiver.java:198) [bundleFile:?]

2020-01-09 20:45:53.478 [INFO ] [covery.EnOceanDeviceDiscoveryService] - Stopping EnOcean discovery scan

Even if I attach the Rollershutter manually, it doesn't work at all.
Do you have any hint/advice for me?

**Comment by fruggy83** [comment]
HI @vio2000,

most of the Eltako actuator cannot be auto discovered except Eltako sensors. You first have to define a rollershutter thing manually:
 * Sending EEP should be FSB14/61/71
 * Receiving EEP FSB14/61/71 AND PTM200
 * Set correct EnOceanId and choose an unique SenderId
Then you have to pair this thing with your actuator:
 * Link the Teach in channel to a switch item (you find it under more)
 * Activate the Teach in mode of your actuator, it depends on the if you have already teached in something or not look [here](https://www.eltako.com/fileadmin/downloads/de/_bedienung/TF61J-230V_30200032-1_dt.pdf)
 * After activating the teach in mode, switch your teach in item => Pairing should be completed.

As these actuators do not send an absolute position you have to set up the shut time (time it needs to close the rollershutter) in the rollershutter channel.

**Comment by vio2000** [comment]
Hi @fruggy83 
thank you. It's working now.

**Comment by fruggy83** [comment]
Glad to hear that it works now 👍
