### ISSUE TITLE
Eltako TF61J

### ISSUE THREAD

**Issue by bitDealer** [fruggy83/openocean#93]
Hey, ich steh glaub irgendwie auf dem Schlauch...
Ich hab im Haus an jedem Rolladen ein Tipp-Funk-Jalousieaktro TF61J-230V installiert. Die sind alle Unterputz, hab aber mal zwei rausgepult, und da steht definitv nirgends die EnoceanId drauf. Wo bekomm ich die her?
An den Aktoren kann man laut Herrsteller-Datenblatt einen Lernmodus aktivieren, ich vermute mal, das ist der "Teach-in"-Mode. Ich habe also über die PaperUI ein neues Thing (Rollershutter) angelegt, bei der EnoceanId muss ich ja aber was eintragen, damit ich das Thing überhaupt erst anlegen kann, um dann den "Teach-In-Switch" aktivieren zu können.
Wo ist mein Denkfehler, weil grade siehts so aus, als bräuchte ich die EnoceanId, um die EnoceanID rauszufinden...
Ich benutze übrigens einen USB300, und meine Taster konnte ich per Auto-Discovery einbinden

**Comment by fruggy83** [comment]
HI @bitDealer,

am einfachsten kommst du über das openhab log an die benötigten Ids. Aktiviere einfach das debug log für das Binding und trigger die Aktoren mit deinen physischen Tastern. Du siehst dann mehrere Einträge im Log mit den Ids. Aufpassen, dass du die richtige Id erwischst. Der Taster sendet zwei Telegramme: Taster gedrückt, Taster losgelassen.

Gruß
Daniel

**Comment by bitDealer** [comment]
Hi Daniel,
danke für deine Antwort. Die ID hab ich jetzt ausgelesen bekommen, lag glaub dran, dass ich noch die Bestätigungs-Telegramme am Aktor aktivieren musste.
Wenn ich jetzt den festverdrahteten Schalter am Aktor drücke, ploppt sogar im Autodiscovery ein neues Thing auf, aber nur als "Simple Push Button".
Hab also die Id aus dem Log genommen, und mir manuell ein Rollershutter Actor mit ebendieser enoceanID angelegt, EEP für Senden und Empfangen habe ich Eltako FSB14/61/71 verwendet.
Vom Thing hab ich mal alle verfügbaren Channels gelinkt, und wenn ich meinen physischen Taster drücke, scheint Openhab auch was zu empfangen, da sich die Channels lastReceived, repeatCount und rssi aktualisieren. Leider passiert aber nix, wenn ich in Openhab hoch, oder runterfahren drücke.
Auch, wenn ich beim Aktor den Lernmodus freischalte, vom Netz trenne und wieder anschließe, und dann den Switch "teachInCMD" betätige, passiert leider nix. Ich hab das Gefühl, ich übersehe irgendwas... Hier mal noch der Log vom grade beschriebenen Verhalten. Hat das was mit der Exception zu tun? Bei der SenderId scheints auch noch ein Problem zu geben, ich hatte die beim Anlegen freigelassen, damit OpenHAB die automatisch setzt, wurde dann auf -4 gesetzt, daher der Configuration Error. Hab sie dann händisch auf 5 gesetzt.

```
2020-05-10 13:43:27.664 [INFO ] [covery.EnOceanDeviceDiscoveryService] - Stopping EnOcean discovery scan
2020-05-10 13:43:27.671 [INFO ] [covery.EnOceanDeviceDiscoveryService] - Starting EnOcean discovery and accepting teach in requests
2020-05-10 13:43:48.440 [INFO ] [ernal.transceiver.EnOceanTransceiver] - Received teach in message from 05082F90
2020-05-10 13:43:48.449 [INFO ] [covery.EnOceanDeviceDiscoveryService] - EnOcean Package discovered, RORG RPS, payload F60105082F9030, additional 00FFFFFFFF5900
==> /var/log/openhab2/events.log <==
2020-05-10 13:43:48.470 [home.event.InboxAddedEvent] - Discovery Result with UID 'enocean:pushButton:FT411INO:05082F90' has been added.
==> /var/log/openhab2/openhab.log <==
2020-05-10 13:43:48.470 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'enocean:pushButton:FT411INO:05082F90' to inbox.
2020-05-10 13:43:49.959 [INFO ] [ernal.transceiver.EnOceanTransceiver] - Received teach in message from 05082F90
2020-05-10 13:43:49.969 [INFO ] [covery.EnOceanDeviceDiscoveryService] - EnOcean Package discovered, RORG RPS, payload F60205082F9030, additional 00FFFFFFFF5C00
2020-05-10 13:43:51.350 [INFO ] [ernal.transceiver.EnOceanTransceiver] - Received teach in message from 05082F90
2020-05-10 13:43:51.356 [INFO ] [covery.EnOceanDeviceDiscoveryService] - EnOcean Package discovered, RORG RPS, payload F60105082F9030, additional 00FFFFFFFF5C00
2020-05-10 13:44:08.806 [ERROR] [ernal.transceiver.EnOceanTransceiver] - Exception in informListeners
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_222]
	at java.lang.Long.parseLong(Long.java:601) ~[?:1.8.0_222]
	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.informListeners(EnOceanTransceiver.java:287) [bundleFile:?]
	at org.openhab.binding.enocean.internal.transceiver.EnOceanESP3Transceiver.processMessage(EnOceanESP3Transceiver.java:151) [bundleFile:?]
	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.receivePackets(EnOceanTransceiver.java:247) [bundleFile:?]
	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.access$2(EnOceanTransceiver.java:241) [bundleFile:?]
	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver$1.run(EnOceanTransceiver.java:192) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
2020-05-10 13:44:15.849 [INFO ] [ernal.transceiver.EnOceanTransceiver] - Received teach in message from 05082F90
2020-05-10 13:44:15.862 [INFO ] [covery.EnOceanDeviceDiscoveryService] - EnOcean Package discovered, RORG RPS, payload F60105082F9030, additional 00FFFFFFFF5B00
2020-05-10 13:44:27.671 [INFO ] [covery.EnOceanDeviceDiscoveryService] - Stopping EnOcean discovery scan
==> /var/log/openhab2/events.log <==
2020-05-10 13:46:00.214 [hingStatusInfoChangedEvent] - 'enocean:rollershutter:7f9a5555' changed from UNINITIALIZED to INITIALIZING
2020-05-10 13:46:00.413 [me.event.ThingUpdatedEvent] - Thing 'enocean:rollershutter:7f9a5555' has been updated.
2020-05-10 13:46:00.440 [.ItemChannelLinkAddedEvent] - Link 'enocean_rollershutter_7f9a5555_rollershutter-enocean:rollershutter:7f9a5555:rollershutter' has been added.
2020-05-10 13:46:00.468 [hingStatusInfoChangedEvent] - 'enocean:rollershutter:7f9a5555' changed from INITIALIZING to OFFLINE (CONFIGURATION_ERROR): Sender Id is not valid for bridge
2020-05-10 13:46:37.373 [me.event.ThingUpdatedEvent] - Thing 'enocean:rollershutter:7f9a5555' has been updated.
2020-05-10 13:46:37.390 [vent.ConfigStatusInfoEvent] - ConfigStatusInfo [configStatusMessages=[]]
2020-05-10 13:46:37.552 [me.event.ThingUpdatedEvent] - Thing 'enocean:rollershutter:7f9a5555' has been updated.
2020-05-10 13:46:37.565 [hingStatusInfoChangedEvent] - 'enocean:rollershutter:7f9a5555' changed from OFFLINE (CONFIGURATION_ERROR): Sender Id is not valid for bridge to ONLINE
2020-05-10 13:46:37.594 [vent.ConfigStatusInfoEvent] - ConfigStatusInfo [configStatusMessages=[]]
2020-05-10 13:46:57.317 [.ItemChannelLinkAddedEvent] - Link 'enocean_rollershutter_7f9a5555_lastReceived-enocean:rollershutter:7f9a5555:lastReceived' has been added.
2020-05-10 13:46:57.953 [.ItemChannelLinkAddedEvent] - Link 'enocean_rollershutter_7f9a5555_repeatCount-enocean:rollershutter:7f9a5555:repeatCount' has been added.
2020-05-10 13:46:58.682 [.ItemChannelLinkAddedEvent] - Link 'enocean_rollershutter_7f9a5555_rssi-enocean:rollershutter:7f9a5555:rssi' has been added.
2020-05-10 13:46:59.329 [.ItemChannelLinkAddedEvent] - Link 'enocean_rollershutter_7f9a5555_teachInCMD-enocean:rollershutter:7f9a5555:teachInCMD' has been added.
2020-05-10 13:47:52.381 [vent.ItemStateChangedEvent] - enocean_rollershutter_7f9a5555_rollershutter changed from NULL to 0
2020-05-10 13:47:52.429 [vent.ItemStateChangedEvent] - enocean_rollershutter_7f9a5555_lastReceived changed from NULL to 2020-05-10T13:47:52.366+0200
2020-05-10 13:47:52.439 [vent.ItemStateChangedEvent] - enocean_rollershutter_7f9a5555_repeatCount changed from NULL to 0
2020-05-10 13:47:52.447 [vent.ItemStateChangedEvent] - enocean_rollershutter_7f9a5555_rssi changed from NULL to -86
2020-05-10 13:47:52.453 [vent.ItemStateChangedEvent] - enocean_rollershutter_7f9a5555_teachInCMD changed from NULL to OFF
```

Viele Grüße,
Tobias

**Comment by fruggy83** [comment]
Hi Tobias,

welche Version des Binding benutzt du? Die Version hier aus meinem Repo oder die offizielle Version direkt aus openhab installiert? Das Problem mit der Exception sollte eigentlich gelöst sein. Es tauchte immer bei unbekannten Telegrammen auf, wird aber mittlerweile abgefangen.
Ich habe mir mal die Doku zum TF61J besorgt. Im Prinzip machst du schon alles richtig, es fehlt dir nur eine wichtige Info: Die meisten Eltako Aktoren können leider nicht per AutoDiscovery eingelernt werden ;) 
Am besten wir fangen noch einmal von vorne an:
 * Lösche alle deine Things für deinen TF61J
 * Melde dich an der openhab Konsole an und aktiviere das debug log
    *  sudo openhab-cli console, PSW 'habopen'
    *  'log:set default org.openhab.binding.enocean'
    * 'logout'
* Drücke deinen physisschen Taster und schau dir die Meldungen im openhab Log an. Wenn das mit dem Aktivieren des debug logs funktioniert hat, solltest du jetzt auch [DEBUG] Meldungen sehen
* Lege ein neues Thing an, EEP: FSB14, EnOceanId aus Log setzen und SenderId zwischen 1 und 128 auswählen.
* Channel TeachIn mit einem Switch Item linken
* In der Channel Config setzt du als TeachIn Telegram FFF80D80
* Learn Modus des Aktors aktivieren, "Mit einem kurzen 'Ab, Halt' wird die Einlern-Bereitschaft signalisiert." Wahrscheinlich fährt dein Rollo kurz runter und hält.
* TeachIn Item aktivieren => "Nach dem Einlernen eines Tasters wird dies mit einem kurzen 'Ab, Halt' bestätigt" Ich denke mal, dass das erfolgreiche Einlernen durch openhab auch mit einem kurzen 'Ab, Hallt' bestätigt wird

Danach solltest du eigentlich deinen Aktor steuern können. Um auch die korrekte Position ermitteln zu können, musst du in deinem Rollershutter Channel nur noch die Laufzeit eintragen.

Gruß
Daniel

**Comment by bitDealer** [comment]
Hey Daniel,
ich hab dir ja gar nicht mehr gantwortet, sorry! Mittlerweile sind alle Rolläden erfolgreich in OpenHAB eingebunden, ich erinnere mich leider nicht mehr genau, was die Lösung war, allerdings wars ein typischer User-Error und kein Software-Problem xD
Lediglich mit zwei Rollos kämpfe ich noch ein wenig, die fahren nicht zu 100% auf bzw. zu...
Danke dir für deine Zeit und Antwort!
